### ISSUE TITLE
Fails on `bundle exec guard`

### ISSUE THREAD

**Issue by michaelparenteau** [stevehodgkiss/sinatra-asset-pipeline#2] opened 2011-09-11 03:12 UTC
Here are the errors that come back:

```
Please install rb-fsevent gem for Mac OSX FSEvents support
Using polling (Please help us to support your system better than that.)
Please install growl or growl_notify gem for Mac OS X notification support and add it to your Gemfile
ERROR: Could not load 'guard/sprockets2' or find class Guard::Sprockets2
ERROR: no such file to load -- rake
ERROR: Invalid Guardfile, original error is:
undefined method `new' for nil:NilClass
```

Any thoughts why this might be?

**Comment by stevehodgkiss** [comment] 2011-09-11 11:46
I've added the rb-fsevent and growl gems for mac. When I run it I get:

``` bash
~/projects/sinatra-asset-pipeline[master]% bundle exec guard
Guard is now watching at '/Users/steve/projects/sinatra-asset-pipeline'
Compiling assets... completed in 0.144542 seconds
```

Pull the latest from github and try running bundle update?

**Comment by dekart** [comment] 2011-09-18 11:25
Fails for me as well:

```
$ bundle exec guard
ERROR: Could not load 'guard/sprockets2' or find class Guard::Sprockets2
ERROR: no such file to load -- rake
ERROR: Invalid Guardfile, original error is:
undefined method `new' for nil:NilClass
```

rb-fsevent and growl are installed

**Comment by stevehodgkiss** [comment] 2011-09-18 11:38
It looks like this was a bug guard-sprockets2, it was requiring rake when it didn't have it as a dependency in the gemspec. Not sure why I couldn't reproduce it though. I've just pushed the fix to this repository, or you can run bundle update to get the latest guard-sprockets2 gem.

Let me know if this fixes it for you.

**Comment by dekart** [comment] 2011-09-18 11:54
Works fine now. Thank you :)

2011/9/18 Steve Hodgkiss
reply@reply.github.com:

> It looks like this was a bug guard-sprockets2, it was requiring rake when it didn't have it as a dependency in the gemspec. Not sure why I couldn't reproduce it though. I've just pushed the fix to this repository, or you can run bundle update to get the latest guard-sprockets2 gem.
> 
> Let me know if this fixes it for you.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/stevehodgkiss/sinatra-asset-pipeline/issues/2#issuecomment-2126367

## 

Alex V. Dmitriev
Jabber/GTalk/MSN/AIM: rene.dekart@gmail.com
Skype: rene-dekart
Blog: http://railorz.ru

**Comment by stevehodgkiss** [comment] 2011-09-18 11:59
No problem :)

**Closed as completed by stevehodgkiss** 2011-09-18 11:59 UTC
